### ISSUE TITLE
Docker writes a lot of data outside /data

### ISSUE THREAD

**Issue by kelson42** [openzim/kalite#10]
Docker should write (almost) nothing outside `/data`. But here this is the case and `/var/lib/docker/aufs` is big for me an fills my whole root filesystem.

```
$ sudo du -sh /var/lib/docker/aufs
202G	/var/lib/docker/aufs
```

**Comment by dattaz** [comment]
Kalitezim work by doing a cache inside /home/$USER/.kalite. But we maybe can avoid that

**Comment by kelson42** [comment]
Yes, not sure a cache makes sense here.... or at least in /data

**Comment by kelson42** [comment]
Effort discontinued, see `README.md`
