### ISSUE TITLE
Video should be (if possible) directly downloaded from Youtube

### ISSUE THREAD

**Issue by kelson42** [openzim/kalite#2]
<a href="https://github.com/kelson42"><img src="https://avatars3.githubusercontent.com/u/1029718?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kelson42](https://github.com/kelson42)**
_Monday Apr 11, 2016 at 17:51 GMT_
_Originally opened as https://github.com/benjaoming/ka-lite-zim/issues/2_

----

Youtube provide often a webm version of videos. This should be downloaded if possible to avoid re-encoding.

**Comment by dattaz** [comment]
Currently, we download videos from a mirror maintained by https://learningequality.org/ka-lite/. Is there any reason to use this mirror of mp4 and not youtube ?

**Comment by rgaudin** [comment]
840eeba97598abe851171d02f8880b4cf9482f37 fixed this already (see #3).

**Comment by dattaz** [comment]
I agree #2 and #3 go together.
But I'm not sure your commit here is OK, for 2 reasons:
- Youtube-dl seems to re-download video and then encoding webm
- Videos (download in mp4, reencoded in webm) are not in the right folder.

Maybe the best thing to do is, using youtube-dl to download video (not the mirror), preferably in webm, if not available reencode in webm from mp4
