### ISSUE TITLE
Subtitles are not available at all

### ISSUE THREAD

**Issue by kelson42** [openzim/kalite#8]
The video player provides the videos but there is no "subtitle button" displayed to get a subtitle (in French for example).

**Comment by benjaoming** [comment]
Notice that subtitles are in "content packs" and that there is no immediate correspondence between the various language version of Khan Academy. Some are dubbed, some are subtitled, some are old, some are new. It's chaos.

You would probably want to build 1 ZIM per KA Lite content pack.

Notice that KA Lite content packs are no longer being built. The last one was in 2017 for 0.17.

**Comment by dattaz** [comment]
I've have some explain in readme about that : https://github.com/openzim/kalite/commit/d36f8adc1de49088a494393448ec0b7c7dabfc77
It's only a work around, since some subtitles seems to have a problem to be parse correctly...(so some are still missing) and only english has subtitles for EACH video.

**Comment by kelson42** [comment]
Effort discontinued, see `README.md`
